export const GET_BUSINESS_CATEGORIES_REQUEST =
  "GET_BUSINESS_CATEGORIES_REQUEST";
export const GET_BUSINESS_CATEGORIES_SUCCESS =
  "GET_BUSINESS_CATEGORIES_SUCCESS";
export const GET_BUSINESS_CATEGORIES_FAIL = "GET_BUSINESS_CATEGORIES_FAIL";

export const GET_BUSINESS_CATEGORY_REQUEST = "GET_BUSINESS_CATEGORY_REQUEST";
export const GET_BUSINESS_CATEGORY_SUCCESS = "GET_BUSINESS_CATEGORY_SUCCESS";
export const GET_BUSINESS_CATEGORY_FAIL = "GET_BUSINESS_CATEGORY_FAIL";
